# Generated by Django 3.0.2 on 2020-02-04 02:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_builder', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='date_created',
        ),
        migrations.AddField(
            model_name='quiz',
            name='date_created',
            field=models.DateTimeField(default=datetime.date.today, verbose_name='date created'),
        ),
    ]
